### PR TITLE
feat: upgrade node from 16 to 20

### PR DESCRIPTION
**Pull request by vitorsgomes**
Upgrades action to run using node 20, as node 16 is no longer maintained and github actions is removing its support. (https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

**Testing**

The changes were tested using the commit fb8b73c4d384cec8ad7b9d9abc2a4b622519b18c to run a workflow on the repository [organizations.spa](https://github.com/lessonnine/organizations.spa). The result of the job can be seen here: https://github.com/lessonnine/organizations.spa/actions/runs/8391900002/job/22983507323?pr=2053

image

### CODE REVIEW

**Comment by amrrbakry** [comment]
I think we also need to upgrade the dependencies in the package.json file since we are now using a different node version. What do you think?

**Comment by vitorsgomes** [comment]
> I think we also need to upgrade the dependencies in the package.json file since we are now using a different node version. What do you think?

I just checked here and the dependencies seem to be up to date, probably thanks to Dependabot

**Review by amrrbakry — APPROVED** [review]
LGTM 👍 Thank you so much! If you could also add an entry to the CHANGELOG, that would be great 🏅

**Comment by vitorsgomes** [comment]
> LGTM 👍 Thank you so much! If you could also add an entry to the CHANGELOG, that would be great 🏅

Done here, thanks for reviewing it fb8b73c4d384cec8ad7b9d9abc2a4b622519b18c

**Review by amrrbakry — APPROVED** [review]

**Pull request merged**
